### ISSUE TITLE
MuseError while Building with node

### ISSUE THREAD

**Issue by afkcodes** [vixalien/muse#15]
```
export class MuseError extends Error {
  name = "MuseError";
  code: ERROR_CODE;
  constructor(code: ERROR_CODE, message: string, options?: ErrorOptions) {
    super(message, options);
    this.code = code;
  }
```
ErrorOptions is not defined or found. also at the same time super accepts only one param but options is also being passed.

**Comment by vixalien** [comment]
where are you using muse? ErrorOptions should be defined by typescript itself

**Comment by afkcodes** [comment]
installed via npm and when i build it says error you can try out once i cloned the code as well and its undefined there too.

**Comment by afkcodes** [comment]
@vixalien any update ?

**Comment by vixalien** [comment]
If you installed the package via npm, you shouldn't be building it as it's already built. You should be getting JS files instead of TS.

Can you post the actual command and full stack trace please?

**Comment by vixalien** [comment]
Feel free to re-open when you run into this again
