### ISSUE TITLE
Adding search filter returns no result

### ISSUE THREAD

**Issue by zWolfrost** [vixalien/muse#3]
Adding a filter to the search function returns no result, or at least i think so. Did i at least do everything correctly?

Here is my code:
`search("Change Deftones", { filter: "songs" }).then(data => console.log(data));`

Here is the result.
```
{
  top_result: null,
  did_you_mean: null,
  categories: [ { title: 'Songs', filter: 'songs', results: [Array] } ],    
  continuation: 'EqgDEg9DaGFuZ2UgRGVmdG9u...',
  autocorrect: null,
  filters: [
    'songs',
    'videos',
    'albums',
    'featured_playlists',
    'community_playlists',
    'artists'
  ]
}
```

**Comment by zWolfrost** [comment]
I'm an idiot. the results are in data.categories[0].results. Hope someone got a good laugh off of that ;)

**Comment by zWolfrost** [comment]
I'm an idiot, the results are in data.categories[0].results. Hope someone got a good laugh off of this 🤦‍♂️

**Comment by vixalien** [comment]
it's okay, and you are not an idiot :)
