### ISSUE TITLE
Unable to get the get_artist_albums working.

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [vixalien/muse#6]
Hi,
Below is my working code so far. I am able to get the artist details but it fails to fetch the albums. I even tried with a time delay, and I tried with passing channelId, browseId from the albums, but none seem to work. Could you please assist with the issue?

    const { get_artist, search, get_artist_albums } = require("libmuse");

    search("eminem", { filter: "artists" }).then(data => {
        // console.log(data)
        const artist = data.top_result.browseId;
        // get_artist(artist).then(data => get_artist_albums(artist, {}).then(data => console.log(data)));
        get_artist(artist).then(data => {
            console.log(data)
            setTimeout(function(){ get_artist_albums(data.albums.browseId, data.albums.params).then(data => console.log(data)) }, 3000);
        });
    })

**Comment by vixalien** [comment]
It is indeed broken. I'm working on a fix.

**Comment by vixalien** [comment]
fixed!
