### ISSUE TITLE
GET_ALBUM returns the videoId of the Youtube video instead of the actual music track from the ytMusic. 

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [vixalien/muse#7]
Consider the foloowing code

```js
const album = "MPREb_jcNZuIQM5me"; // Album: Curtain Call 2 - Singer: Eminem - Album Link: https://music.youtube.com/playlist?list=OLAK5uy_niAPdRC-UM6CbmUaldt6_FUgIhSb2gayM

get_album(album).then(data => {
    const tracksLength = data.tracks.length; // 35 Songs

    const track = data.tracks[0] // First Song i.e. Godzilla (feat. Juice WRLD) - VideoID: r_0JjYUe5jo
})
```

The get_album returns the `videoId` of the actual youtube video(`r_0JjYUe5jo`). How can we get the videoId of the song from ytmusic(`5UpETVVdRaA`)?

Thanks & Regards,
Utkarsh Vishnoi

**Comment by vixalien** [comment]
YouTube Music can be ambiguous at times. There are 2 different album IDs: `MPREb_WALokSukf0y` and `MPREb_jcNZuIQM5me`, which both point to the same album. However, the first (ending with `0y`) is explicit, while the other one you sent (ending with `me`) is not explicit. (Not Explicit means profanity has been silenced for easier marketability.)

If you do `get_album("MPREb_WALokSukf0y")`, you will see that the first track has a video ID of `5UpETVVdRaA` which is what you're looking for.

ProTip: You can get other album versions with:

```js
get_album(album).then(data => {
    const other_versions = data.other_versions;
})
```

**Comment by Utkarsh-vishnoi** [comment]
It's not working for me. I tried executing the below piece of code.

    get_album("MPREb_WALokSukf0y").then(data => {
        const track = data.tracks[0]
        console.log(track.videoId)
    })

    get_album("MPREb_jcNZuIQM5me").then(data => {
        const track = data.tracks[0]
        console.log(track.videoId)
    })

The output is as follows:

    r_0JjYUe5jo
    r_0JjYUe5jo

It's printing the same videoId for both the albums. 

Thanks for the pro-tip. Could it be that I am doing something wrong? Please point me in the right direction.

Thanks & Regards,
Utkarsh Vishnoi

**Comment by Utkarsh-vishnoi** [comment]
Hi,

Any update here.

**Comment by vixalien** [comment]
Hello. It seems it's just weird Youtube Music behaviour depending on your country. It may mean that the album is geo-restricted in your country.

Can you see if the same behaviour applies for other albums?

**Comment by vixalien** [comment]
I am going to close this issue for lack of information. Please feel free to reopen the discussion
